# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'angles_input.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(373, 387)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 40, 171, 333))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.channel_Designation = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.channel_Designation.setStyleSheet("background-color: rgb(255, 255, 255);\n"
        "")
        self.channel_Designation.setObjectName("channel_Designation")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.channel_Designation)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.channel_Mass = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.channel_Mass.setStyleSheet("background-color: rgb(255, 255, 255);\n"
        "\n"
        "")
        self.channel_Mass.setObjectName("channel_Mass")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.channel_Mass)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.Area = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.Area.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Area.setObjectName("Area")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Area)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.channel_D = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.channel_D.setStyleSheet("background-color: rgb(255, 255, 255);\n"
        "\n"
        "")
        self.channel_D.setObjectName("channel_D")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.channel_D)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.channel_B = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.channel_B.setStyleSheet("background-color: rgb(255, 255, 255);\n"
        "")
        self.channel_B.setObjectName("channel_B")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.channel_B)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.channel_tw = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.channel_tw.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.channel_tw.setObjectName("channel_tw")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.channel_tw)
        self.channel_T = QtWidgets.QLabel(self.formLayoutWidget)
        self.channel_T.setObjectName("channel_T")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.channel_T)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_15.setStyleSheet("background-color: rgb(255, 255, 255);\n"
        "")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_15)
        self.channel_FlangeSlope = QtWidgets.QLabel(self.formLayoutWidget)
        self.channel_FlangeSlope.setObjectName("channel_FlangeSlope")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.channel_FlangeSlope)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_16.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_16)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.channel_R1 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.channel_R1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.channel_R1.setObjectName("channel_R1")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.channel_R1)
        self.label_27 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_27.setObjectName("label_27")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.channel_R2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.channel_R2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
        "")
        self.channel_R2.setObjectName("channel_R2")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.channel_R2)
        self.label_28 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_28.setObjectName("label_28")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.channel_Iz = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.channel_Iz.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.channel_Iz.setObjectName("channel_Iz")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.channel_Iz)
        self.label_37 = QtWidgets.QLabel(Dialog)
        self.label_37.setGeometry(QtCore.QRect(20, 10, 241, 20))
        self.label_37.setStyleSheet("color: rgb(0, 170, 0);\n"
        "font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_37.setObjectName("label_37")
        self.formLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(200, 40, 151, 331))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_29 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_29.setObjectName("label_29")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.channel_Iy = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.channel_Iy.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.channel_Iy.setObjectName("channel_Iy")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.channel_Iy)
        self.label_30 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_30.setObjectName("label_30")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.channel_rz = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.channel_rz.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.channel_rz.setObjectName("channel_rz")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.channel_rz)
        self.label_31 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_31.setObjectName("label_31")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.channel_ry = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.channel_ry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.channel_ry.setObjectName("channel_ry")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.channel_ry)
        self.label_32 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_32.setObjectName("label_32")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.channel_zz = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.channel_zz.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.channel_zz.setObjectName("channel_zz")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.channel_zz)
        self.label_33 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_33.setObjectName("label_33")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.channel_Zy = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.channel_Zy.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.channel_Zy.setObjectName("channel_Zy")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.channel_Zy)
        self.label_34 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_34.setObjectName("label_34")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.channel_Zpz = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.channel_Zpz.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.channel_Zpz.setObjectName("channel_Zpz")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.channel_Zpz)
        self.label_35 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_35.setObjectName("label_35")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.channel_Zpy = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.channel_Zpy.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.channel_Zpy.setObjectName("channel_Zpy")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.channel_Zpy)
        self.label_36 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_36.setObjectName("label_36")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.channel_Source = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.channel_Source.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.channel_Source.setObjectName("channel_Source")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.channel_Source)
        self.label_38 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_38.setObjectName("label_38")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.channel_Source_2 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.channel_Source_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.channel_Source_2.setObjectName("channel_Source_2")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.channel_Source_2)
        self.channel_Source_3 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.channel_Source_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.channel_Source_3.setObjectName("channel_Source_3")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.channel_Source_3)
        self.label_39 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_39.setObjectName("label_39")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.channel_push_submit = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.channel_push_submit.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.channel_push_submit.setObjectName("channel_push_submit")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.SpanningRole, self.channel_push_submit)
        self.channel_push_submit.clicked.connect(self.abc)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Designation"))
        self.label.setText(_translate("Dialog", "Mass"))
        self.label_3.setText(_translate("Dialog", "t"))
        self.label_4.setText(_translate("Dialog", "R1"))
        self.label_15.setText(_translate("Dialog", "R2"))
        self.label_14.setText(_translate("Dialog", "Cz"))
        self.channel_T.setText(_translate("Dialog", "Cy"))
        self.channel_FlangeSlope.setText(_translate("Dialog", "Tan?"))
        self.label_17.setText(_translate("Dialog", "Iz"))
        self.label_27.setText(_translate("Dialog", "Iy"))
        self.label_28.setText(_translate("Dialog", "Iu(max)"))
        self.label_37.setText(_translate("Dialog", "Enter Angle details"))
        self.label_29.setText(_translate("Dialog", "Iv(min)"))
        self.label_30.setText(_translate("Dialog", "rz"))
        self.label_31.setText(_translate("Dialog", "ry"))
        self.label_32.setText(_translate("Dialog", "ru(max)"))
        self.label_33.setText(_translate("Dialog", "rv(min)"))
        self.label_34.setText(_translate("Dialog", "Zz"))
        self.label_35.setText(_translate("Dialog", "Zy"))
        self.label_36.setText(_translate("Dialog", "Zpz"))
        self.label_38.setText(_translate("Dialog", "Zpy"))
        self.label_39.setText(_translate("Dialog", "Source"))
        self.channel_push_submit.setText(_translate("Dialog", "Submit"))
    def abc(self):
        print("hhhhhhhhhhhhhhhhhhhhhhhhhh")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

