# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detailsangles.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(472, 455)
        Dialog.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"border-color: rgb(0, 0, 127);")
        self.label_37 = QtWidgets.QLabel(Dialog)
        self.label_37.setGeometry(QtCore.QRect(20, 10, 241, 16))
        self.label_37.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_37.setObjectName("label_37")
        self.label_65 = QtWidgets.QLabel(Dialog)
        self.label_65.setGeometry(QtCore.QRect(250, 10, 241, 16))
        self.label_65.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_65.setText("")
        self.label_65.setObjectName("label_65")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(30, 410, 131, 23))
        self.pushButton.setStyleSheet("background-color: rgb(107, 107, 107);\n"
"background-color: rgb(255, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.D_push_submit = QtWidgets.QPushButton(Dialog)
        self.D_push_submit.setGeometry(QtCore.QRect(260, 410, 141, 23))
        self.D_push_submit.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.D_push_submit.setObjectName("D_push_submit")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(21, 44, 394, 346))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.d_label_2 = QtWidgets.QLabel(self.widget)
        self.d_label_2.setObjectName("d_label_2")
        self.gridLayout.addWidget(self.d_label_2, 0, 0, 1, 1)
        self.d_linedit_A = QtWidgets.QLineEdit(self.widget)
        self.d_linedit_A.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.d_linedit_A.setObjectName("d_linedit_A")
        self.gridLayout.addWidget(self.d_linedit_A, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.d_linedit_B = QtWidgets.QLineEdit(self.widget)
        self.d_linedit_B.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.d_linedit_B.setObjectName("d_linedit_B")
        self.gridLayout.addWidget(self.d_linedit_B, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.d_linedit_C = QtWidgets.QLineEdit(self.widget)
        self.d_linedit_C.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.d_linedit_C.setObjectName("d_linedit_C")
        self.gridLayout.addWidget(self.d_linedit_C, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.d_linedit_D = QtWidgets.QLineEdit(self.widget)
        self.d_linedit_D.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.d_linedit_D.setObjectName("d_linedit_D")
        self.gridLayout.addWidget(self.d_linedit_D, 3, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 4, 0, 1, 1)
        self.d_linedit_E = QtWidgets.QLineEdit(self.widget)
        self.d_linedit_E.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.d_linedit_E.setObjectName("d_linedit_E")
        self.gridLayout.addWidget(self.d_linedit_E, 4, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 5, 0, 1, 1)
        self.d_linedit_F = QtWidgets.QLineEdit(self.widget)
        self.d_linedit_F.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.d_linedit_F.setObjectName("d_linedit_F")
        self.gridLayout.addWidget(self.d_linedit_F, 5, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 6, 0, 1, 1)
        self.d_linedit_G = QtWidgets.QLineEdit(self.widget)
        self.d_linedit_G.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.d_linedit_G.setObjectName("d_linedit_G")
        self.gridLayout.addWidget(self.d_linedit_G, 6, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 7, 0, 1, 1)
        self.d_linedit_H = QtWidgets.QLineEdit(self.widget)
        self.d_linedit_H.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.d_linedit_H.setObjectName("d_linedit_H")
        self.gridLayout.addWidget(self.d_linedit_H, 7, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 8, 0, 1, 1)
        self.d_linedit_I = QtWidgets.QLineEdit(self.widget)
        self.d_linedit_I.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.d_linedit_I.setObjectName("d_linedit_I")
        self.gridLayout.addWidget(self.d_linedit_I, 8, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.widget)
        self.label_51.setObjectName("label_51")
        self.gridLayout.addWidget(self.label_51, 9, 0, 1, 1)
        self.d_linedit_J = QtWidgets.QLineEdit(self.widget)
        self.d_linedit_J.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.d_linedit_J.setObjectName("d_linedit_J")
        self.gridLayout.addWidget(self.d_linedit_J, 9, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.widget)
        self.label_52.setObjectName("label_52")
        self.gridLayout.addWidget(self.label_52, 10, 0, 1, 1)
        self.d_linedit_K = QtWidgets.QLineEdit(self.widget)
        self.d_linedit_K.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.d_linedit_K.setObjectName("d_linedit_K")
        self.gridLayout.addWidget(self.d_linedit_K, 10, 1, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.widget)
        self.label_64.setObjectName("label_64")
        self.gridLayout.addWidget(self.label_64, 11, 0, 1, 1)
        self.d_linedit_L_2 = QtWidgets.QLineEdit(self.widget)
        self.d_linedit_L_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.d_linedit_L_2.setObjectName("d_linedit_L_2")
        self.gridLayout.addWidget(self.d_linedit_L_2, 11, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_53 = QtWidgets.QLabel(self.widget)
        self.label_53.setObjectName("label_53")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_53)
        self.d_linedit_M = QtWidgets.QLineEdit(self.widget)
        self.d_linedit_M.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.d_linedit_M.setObjectName("d_linedit_M")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.d_linedit_M)
        self.label_54 = QtWidgets.QLabel(self.widget)
        self.label_54.setObjectName("label_54")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_54)
        self.d_linedit_N = QtWidgets.QLineEdit(self.widget)
        self.d_linedit_N.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.d_linedit_N.setObjectName("d_linedit_N")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.d_linedit_N)
        self.label_55 = QtWidgets.QLabel(self.widget)
        self.label_55.setObjectName("label_55")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_55)
        self.d_linedit_O = QtWidgets.QLineEdit(self.widget)
        self.d_linedit_O.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.d_linedit_O.setObjectName("d_linedit_O")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.d_linedit_O)
        self.label_56 = QtWidgets.QLabel(self.widget)
        self.label_56.setObjectName("label_56")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_56)
        self.d_linedit_P = QtWidgets.QLineEdit(self.widget)
        self.d_linedit_P.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.d_linedit_P.setObjectName("d_linedit_P")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.d_linedit_P)
        self.label_57 = QtWidgets.QLabel(self.widget)
        self.label_57.setObjectName("label_57")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_57)
        self.d_linedit_Q = QtWidgets.QLineEdit(self.widget)
        self.d_linedit_Q.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.d_linedit_Q.setObjectName("d_linedit_Q")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.d_linedit_Q)
        self.label_58 = QtWidgets.QLabel(self.widget)
        self.label_58.setObjectName("label_58")
        self.formLayout_5.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_58)
        self.d_linedit_R = QtWidgets.QLineEdit(self.widget)
        self.d_linedit_R.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.d_linedit_R.setObjectName("d_linedit_R")
        self.formLayout_5.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.d_linedit_R)
        self.label_59 = QtWidgets.QLabel(self.widget)
        self.label_59.setObjectName("label_59")
        self.formLayout_5.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_59)
        self.d_linedit_S = QtWidgets.QLineEdit(self.widget)
        self.d_linedit_S.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.d_linedit_S.setObjectName("d_linedit_S")
        self.formLayout_5.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.d_linedit_S)
        self.label_60 = QtWidgets.QLabel(self.widget)
        self.label_60.setObjectName("label_60")
        self.formLayout_5.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_60)
        self.d_linedit_T = QtWidgets.QLineEdit(self.widget)
        self.d_linedit_T.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.d_linedit_T.setObjectName("d_linedit_T")
        self.formLayout_5.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.d_linedit_T)
        self.label_61 = QtWidgets.QLabel(self.widget)
        self.label_61.setObjectName("label_61")
        self.formLayout_5.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_61)
        self.d_linedit_U = QtWidgets.QLineEdit(self.widget)
        self.d_linedit_U.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.d_linedit_U.setObjectName("d_linedit_U")
        self.formLayout_5.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.d_linedit_U)
        self.label_62 = QtWidgets.QLabel(self.widget)
        self.label_62.setObjectName("label_62")
        self.formLayout_5.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_62)
        self.d_linedit_V = QtWidgets.QLineEdit(self.widget)
        self.d_linedit_V.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.d_linedit_V.setObjectName("d_linedit_V")
        self.formLayout_5.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.d_linedit_V)
        self.d_label_A = QtWidgets.QLabel(self.widget)
        self.d_label_A.setObjectName("d_label_A")
        self.formLayout_5.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.d_label_A)
        self.d_linedit_W = QtWidgets.QLineEdit(self.widget)
        self.d_linedit_W.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.d_linedit_W.setObjectName("d_linedit_W")
        self.formLayout_5.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.d_linedit_W)
        self.horizontalLayout.addLayout(self.formLayout_5)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_37.setText(_translate("Dialog", "Enter Angle details"))
        self.pushButton.setText(_translate("Dialog", "Clear"))
        self.D_push_submit.setText(_translate("Dialog", "Submit"))
        self.d_label_2.setText(_translate("Dialog", "Designation"))
        self.label.setText(_translate("Dialog", "Mass"))
        self.label_3.setText(_translate("Dialog", "Area"))
        self.label_4.setText(_translate("Dialog", "AxB"))
        self.label_15.setText(_translate("Dialog", "t"))
        self.label_14.setText(_translate("Dialog", "R1"))
        self.label_13.setText(_translate("Dialog", "R2"))
        self.label_16.setText(_translate("Dialog", "Cz"))
        self.label_17.setText(_translate("Dialog", "Cy"))
        self.label_51.setText(_translate("Dialog", "Tan?"))
        self.label_52.setText(_translate("Dialog", "Iz"))
        self.label_64.setText(_translate("Dialog", "Iy"))
        self.label_53.setText(_translate("Dialog", "Iu(max)"))
        self.label_54.setText(_translate("Dialog", "Iv(min)"))
        self.label_55.setText(_translate("Dialog", "rz"))
        self.label_56.setText(_translate("Dialog", "ry"))
        self.label_57.setText(_translate("Dialog", "ru(max)"))
        self.label_58.setText(_translate("Dialog", "ru(min)"))
        self.label_59.setText(_translate("Dialog", "Zz"))
        self.label_60.setText(_translate("Dialog", "Zy"))
        self.label_61.setText(_translate("Dialog", "Zpz"))
        self.label_62.setText(_translate("Dialog", "Zpy"))
        self.d_label_A.setText(_translate("Dialog", "Source"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

